tunnel: 6c5c424a-2303-44ff-beb3-57b242e61ff7
credentials-file: /etc/cloudflared/6c5c424a-2303-44ff-beb3-57b242e61ff7.json

ingress:
  - hostname: danilanet.id.lv
    service: http://frontend:80

  - hostname: api.danilanet.id.lv
    service: http://backend:5000

  - service: http_status:404